name: FundamentalsItemCore
main: info.somethingodd.odditem.OddItemBase
load: STARTUP
visible: false
version: 1.0.0
authors:
  - petteyg359
  - RhysB
description: A Fundamentals fork of OddItem used for various item name resolutions.
commands:
  odditem:
    aliases: oi
    permission: odditem.alias
    usage: |
      /<command> [alias]
      Shows aliases of held item or <alias>
  odditeminfo:
    aliases: oii
    permission: odditem.info
    usage: |
      /<command>
      Shows information about loaded items/aliases
  odditemreload:
    aliases: oir
    permission: odditem.reload
    usage: |
      /<command>
      Reload configuration from disk
permissions:
  odditem:
    children:
      odditem.alias: true
      odditem.info: true
    default: true
  odditem.alias:
    default: true
  odditem.info:
    default: true
  odditem.reload:
    default: op
