name: Fundamentals
description: A Essentials like plugin for Beta 1.7.3 designed for Project Poseidon
main: com.johnymuffin.beta.fundamentals.Fundamentals
version: 1.0.8
authors:
  - JohnyMuffin
softdepend:
  - DiscordCore
  - UUIDCore
  - JPerms
  - PermissionsEx

commands:
#  heal:
#    description: Heals a player
#    usage: /<command> <player>
  afk:
    description: Toggles your afk status
    usage: /<command> <player>
  back:
    description: Teleports to the location of your last teleport
    usage: /<command>
  hat:
    description: Puts the held block on the players head.
    usage: /<command>
  home:
    description: a home command
    usage: /<command>
    aliases: [h]
  homesearch:
    description: searches through player homes
    usage: /<command> <player> <radius>
    aliases: [hs]
  sethome:
    description: a home command
    usage: /<command>
    aliases: [sh]
  delhome:
    description: a home command
    usage: /<command>
    aliases: [dh]
  homes:
    description: a home command
    usage: /<command>
    aliases: [hl, homelist]
  balance:
    description: a balance command
    usage: /<command>
    aliases: [bal]
#  pay:
#    description: a economy command
#    usage: /<command>
  economy:
    description: a economy command
    usage: /<command>
    aliases: [eco]
#  god:
#    description: a god command
#    usage: /<command>
#  nickname:
#    description: a nickname command
#    usage: /<command>
#    aliases: [nick]
#  invsee:
#    description: a inventory command
#    usage: /<command>
#  clearinventory:
#    description: Clear all items in your inventory.
#    usage: /<command>
#    aliases: [ci]
  vanish:
    description: Command to vanish player.
    usage: /<command>
  weather:
    description: Command to change the weather in a world.
    usage: /<command> <clear|sun|rain|storm> [worldname|all]
  bank:
    description: Command to do bank stuff.
    usage: /<command>
 # time:
 #   description: time change command
 #   usage: /<command> [day|night|dawn|17:30|4pm|4000ticks] [worldname|all]
 #   aliases: [day, night]

 # ptime:
 #   description: player time change command
 #   usage: /<command> [day|night|dawn|17:30|4pm|4000ticks]
 #   aliases: [day, night]
  balancetop:
    description: a balance top command
    usage: /<command>
    aliases: [baltop]
  fakequit:
    description: A command to "fake quit" from the server.
    usage: /<command> <player>
    aliases: [fq,fakejoin,fj]
    
