name: Fundamentals
description: A Essentials like plugin for Beta 1.7.3 designed for Project Poseidon
main: com.johnymuffin.beta.fundamentals.Fundamentals
version: 1.0.7
authors:
  - JohnyMuffin
softdepend:
  - DiscordCore
  - UUIDCore
  - JPerms
  - PermissionsEx

commands:
#  heal:
#    description: Heals a player
#    usage: /<command> <player>
#  afk:
#    description: Set a plad
#    usage: /<command> <player>
  hat:
    description: Puts the held block on the players head.
    usage: /<command>
  home:
    description: a home command
    usage: /<command>
    aliases: [h]
  sethome:
    description: a home command
    usage: /<command>
    aliases: [sh]
  delhome:
    description: a home command
    usage: /<command>
    aliases: [dh]
  balance:
    description: a balance command
    usage: /<command>
    aliases: [bal]
#  pay:
#    description: a economy command
#    usage: /<command>
  economy:
    description: a economy command
    usage: /<command>
    aliases: [eco]
#  god:
#    description: a god command
#    usage: /<command>
#  nickname:
#    description: a nickname command
#    usage: /<command>
#    aliases: [nick]
  realname:
    description: Command to get the real name of a nicked user.
    usage: /<command> <nickname>
  seen:
    description: Command to show when a player was last seen.
    usage: /<command> <player>
#  invsee:
#    description: a inventory command
#    usage: /<command>
#  clearinventory:
#    description: Clear all items in your inventory.
#    usage: /<command>
#    aliases: [ci]
  msg:
    description: Command to message players.
    usage: /<command> <player> <message>
    aliases: [m, t, tell, whisper, w]
  r:
    description: Command to reply to players.
    usage: /<command> <message>
    aliases: [reply]
  mute:
    description: Command to mute players.
    usage: /<command> <player> [duration]
  ignore:
    description: Command to ignore players.
    usage: /<command> <player>
  vanish:
    description: Command to vanish player.
    usage: /<command>
  bank:
    description: Command to do bank stuff.
    usage: /<command>
 # time:
 #   description: time change command
 #   usage: /<command> [day|night|dawn|17:30|4pm|4000ticks] [worldname|all]
 #   aliases: [day, night]

 # ptime:
 #   description: player time change command
 #   usage: /<command> [day|night|dawn|17:30|4pm|4000ticks]
 #   aliases: [day, night]
  balancetop:
    description: a balance top command
    usage: /<command>
    aliases: [baltop]
  fakequit:
    description: A command to "fake quit" from the server.
    usage: /<command> <player>
    aliases:
      - fq
      - fakejoin
      - fj
