name: FundamentalsImporter
description: Essentials data import for Funndamentals
main: com.johnymuffin.fundamentals.importer.FundamentalsESSBridge
version: 1.0.0
authors:
  - JohnyMuffin
depend: [Fundamentals, Essentials]